language: node_js
node_js:
- '14'
- '13'
- '12'
- '11'
- '10'
env:
  global:
    secure:
    sE439XZ7gWHf+JmrUMFwntInxJwv0t7rdY5c7ZnpvM2ewqxds//Cry38K6OnZJBneNDGTuSAbfrDWqIWgUOjtLokP018ndZmIovIiboGvCEz3TExBR+Bbd+VRrnnpTveGwLQ0wz7ZEKPDGRMgklWCIE9J3btmqq/Y3p0iQjGJ0PkdJT2bS04ffbSFCYRRDO3KWHpIlMq7Zm97zIw8YnnwYuQUfJNBA5733PMrul0O6kBJHQXdlhP8IMHa+W/scv1VjlKWMOdWTL/IFuaPWlZZhWe0V3WUOAR/7q/WoIlPJLXK8K+TOsjqLaeDHw4MsvZ3xVgNP1sWBxNxqh1jkZOfeiBOuh4xG1KRV+hwbiJJ4qK25uMm+xCLecfEwMW04GPXMs3IvkSyj2ri3E0XiBWkzwdZzVtlMwTyR1g6M0HcQ+fmd74wZVgqet1rLbj9r/2JdC6jMf0ul40w+NI0QPad97nflyf14X0YdopImQ6oJThFnv9sTMGTdWIc1phVvi+oRsU+fpKMHwN0kh7Tf5efprfseHANVC5iv5oWL7KwZPdnR/6+et9H0zNaxuw2gTDu8IrSaTmpFqVqyR6egkmoaoUcYZQQwlo7lk60siddxL+AiuU4Xi7X99fXRYwdGMqePL/Mnta+3cJ71Y9cJHOfwK3aRrNTUvJzNGwf8IhBnQ=
